from tkinter import *
def getvals():
    print("successful")
    print(phone.get())
root=Tk()
root.geometry("655x455")
Label(root,text="PHONE").grid()
Label(root,text="GENDER").grid(row=1)
Label(root,text="NAME").grid(row=2)
Label(root,text="PAYMENT MODE").grid(row=3)
phone=StringVar()
gender=StringVar()
name=StringVar()
payment=StringVar()
Entry(root,textvariable=phone).grid(row=0,column=1)
Entry(root,textvariable=gender).grid(row=1,column=1)
Entry(root,textvariable=name).grid(row=2,column=1)
Entry(root,textvariable=payment).grid(row=3,column=1)
Checkbutton(text="want to book").grid(row=4,column=3)
Button(text="submit",command=getvals).grid()
root.mainloop()
